project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    # https://bootswatch.com/
    theme: 
      light: [litera, custom.scss]
      dark: cyborg
    # https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
    mainfont: ui-rounded
    css: styles.css
    
editor: visual

